routes/web.php
    <?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => []], function () {
    Route::auth();
    Route::get('/logout', function() {
        Auth::logout();
        //Added for session destroy on logout. Fix for Session Regeneration --AG 310717
        Session::flush();
        return redirect('/login');
    });

    // Route::get('/home', 'HomeController@index')->name('home');
});
Route::group(['middleware' => ['inputcheck','prevent-back-history']], function () {
    Route::get('/', function () {
        return view('home');
        // auth()->user()->assignRole('Super Admin');
    });
});

Route::middleware(['auth', 'aclmiddleware', 'inputcheck',  'prevent-back-history'])->group(function () {
    Route::auth();
    Route::get('/', function () {
        return redirect('/login');
    });

    
    Route::group(['prefix' => 'access-control'], function() {
        Route::resource('users', 'UserController');
        Route::resource('role/role-create', 'UserController@roleCreate');
        // Route::get('role/checkRoleName','RoleController@checkRoleName');
        Route::resource('role', 'RoleController');
        Route::resource('branch-master', 'BranchMasterController');
        Route::resource('data', 'DataController');
        Route::resource('permission', 'PermissionController');
    });

    
    Route::group(['prefix' => '/'], function() {
        // Route::get('/', 'MainPageController@index');
        Route::get('/change_password', 'MainPageController@ChangePassword');
        Route::post('/change_password', 'MainPageController@CheckPassword');

    });
    
    Route::post('/store-file', 'StoreFileController@store_file');
});

Route::post('/store-file', 'StoreFileController@store_file');
Route::get('notify/index', 'NotificationController@index');

Auth::routes();

app/Http/Controllers/RoleController.php
<?php


namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;
use Datatables;


class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct(Role $roles)
    {
        $this->roles = $roles;        
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            // dd(12);
            $data =  Role::get();
            $data = collect($data);
            return Datatables::of($data)->make(true);
        }   

        // $data['columns'] = excludeColumn(getColumnList($this->roles), []);
       // dd(1); 
        $data['columns'] = [];
        $data['columns'] = array_merge(['action','name'], $data['columns'], []);
        // return $data['columns']; // Array to be excluded.
        $data['pk'] = 'id';
        // $data['prefix'] = config('constants.CreditorTypeMaster.prefix');
        $data['disable_footer_column'] = ['action'];
        $data['disable_footer_search'] = [];
        // $data['user_type'] = \Auth::User()->user_type;        
        $data['disable_footer_search'] = getIndex($data['disable_footer_column'], $data['columns']);
        // return $data;
        // return view('data.index',compact('data'))
            // ->with('i', ($request->input('page', 1) - 1) * 5);

        return view('role.role', ['data' => $data]);
        /*$roles = Role::orderBy('id','DESC')->paginate(5);
        // dd(11);
        return view('role.index',compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);*/
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $data['tab'] = sidebarData();

        $data['tab'] = objectToArray($data['tab']);
        $data['screen_name'] = 'role_edit';
        $data['selected_status'] = config('constants.STATUS.active.DB_VALUE');
        $data['readonly'] = ['status'];
        $data['disabled'] = ['status'];
        // return $data;
        return view('role.role_operation',compact('data'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);

        // dd($request->input('permission'));
        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));


        return redirect()->route('role.index')
                        ->with('success','Role created successfully');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Role::find($id);
        if(!isset($data))
        {
            abort(404);
        }

        $rolePermissions = permissionListViaRoles($id);
        
        $data['permission'] = $rolePermissions;
        // dd($data['permission']);
        return $this->createShow($data);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         return $this->show($id);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();
        $role->syncPermissions($request->input('permission'));

        return redirect()->route('role.index')
                        ->with('success','Role updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table("roles")->where('id',$id)->delete();
        return redirect()->route('role.index')
                        ->with('success','Role deleted successfully');
    }

    public function roleCreate()
    {
        $role = Role::create(['name' => 'writer']);
        $permission = Permission::create(['name' => 'edit articles']);
        
        $role->givePermissionTo($permission);
        $permission->assignRole($role);
    }

     public function createShow($data = "") {

        $data['tab'] = sidebarData();
        $data['tab'] = objectToArray($data['tab']);
        $data['screen_name'] = 'role_edit';
        $data['selected_status'] = config('constants.STATUS.active.DB_VALUE');
        $data['readonly'] = ['status'];
        $data['disabled'] = ['status'];

        // return $data['permission'];
        return view('role.role_operation', ['data' => $data]);
    }
}

resources/views/role/create.blade.php
@extends('layouts.app')


@section('main-content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Create New Role</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('role.index') }}"> Back</a>
        </div>
    </div>
</div>


@if (count($errors) > 0)
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
        </ul>
    </div>
@endif


{!! Form::open(array('route' => 'role.store','method'=>'POST')) !!}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Permission:</strong>
            <br/>
            @foreach($permission as $value)
                <label>{{ Form::checkbox('permission[]', $value->id, false, array('class' => 'name')) }}
                {{ $value->name }}</label>
            <br/>
            @endforeach
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
{!! Form::close() !!}


@endsection

resources/views/role/edit.blade.php
@extends('layouts.app')


@section('main-content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Role</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('role.index') }}"> Back</a>
        </div>
    </div>
</div>


@if (count($errors) > 0)
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
        </ul>
    </div>
@endif


{!! Form::model($role, ['method' => 'PATCH','route' => ['role.update', $role->id]]) !!}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Permission:</strong>
            <br/>
            @foreach($permission as $value)
                <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}
                {{ $value->name }}</label>
            <br/>
            @endforeach
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
{!! Form::close() !!}


@endsection

resources/views/role/index.blade.php
@extends('layouts.app')


@section('main-content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Role Management</h2>
        </div>
        <div class="pull-right">
        @can('role-create')
            <a class="btn btn-success" href="{{ route('role.create') }}"> Create New Role</a>
            @endcan
        </div>
    </div>
</div>


@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif


<table class="table table-bordered">
  <tr>
     <th>No</th>
     <th>Name</th>
     <th width="280px">Action</th>
  </tr>
    @foreach ($roles as $key => $role)
    <tr>
        <td>{{ ++$i }}</td>
        <td>{{ $role->name }}</td>
        <td>
            <a class="btn btn-info" href="{{ route('role.show',$role->id) }}">Show</a>
            @can('role-edit')
                <a class="btn btn-primary" href="{{ route('role.edit',$role->id) }}">Edit</a>
            @endcan
            @can('role-delete')
                {!! Form::open(['method' => 'DELETE','route' => ['role.destroy', $role->id],'style'=>'display:inline']) !!}
                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                {!! Form::close() !!}
            @endcan
        </td>
    </tr>
    @endforeach
</table>


{!! $roles->render() !!}


@endsection

resources/views/role/role.blade.php
@extends('layouts.app')

@section('custom-styles')
    
    @include('layouts.style_loaders.token_loader')
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.dataTables.min.css"/>
    <link href="{{ asset('/css/datatables/buttons.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />

@endsection

@section('htmlheader_title')
    {{ucwords(str_replace('-', ' ', Request::segment(1)))}} | {{ucwords(str_replace('-', ' ', Request::segment(2)))}}
@endsection


@section('contentheader_title')
    {{ucwords(str_replace('-', ' ', Request::segment(2)))}}
@endsection


@section('custom-breadcrumb')
    @include('layouts.custom_partials.breadcrumb')
@endsection

@section('contentheader_description')
    
@endsection

@section('main-content')
    
    <div class="panel">
        <div class="panel-body ">   
            <div class = "pull-right">
                <div class="btn-group">
                    <a href="/{{Request::path()}}/create">
                        <label class="btn btn-sharekhan" data-toggle="tooltip" data-target="" title="Add {{ucwords(str_replace('-', ' ', Request::segment(2)))}}" data-original-title="Add {{ucwords(str_replace('-', ' ', Request::segment(2)))}}"><i class="fa fa-plus"></i> Add {{ucwords(str_replace('-', ' ',Request::segment(2)))}}</label>
                    </a>
                </div>
            </div>
        <div class="panel-body padding_top_3">
            <table id="role" class="datatable table display compact table-striped table-bordered  hover nowrap" cellspacing="0" role="grid" width="100%">
                <thead>
                    <tr>
                        @forEach($data['columns'] as $column)
                            <th class = "thead_{{$column}}">{{ucwords(str_replace('_', ' ', $column))}}</th>
                        @endforeach
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        @forEach($data['columns'] as $key => $column)
                            @if(in_array($key ,$data['disable_footer_search']))
                                <th class = "tfoot_{{$column}} no-search"> {{ucwords(str_replace('_', ' ', $column))}} </th>
                            @else
                                <th class = "tfoot_{{$column}}"> {{ucwords(str_replace('_', ' ', $column))}} </th>
                            @endif
                        @endforeach
                    </tr>
                </tfoot>
            </table>
        </div>
        
    </div>

@endsection

@section('php-to-js')
    <?php
        $js_data = array();
        $js_data['env'] = env('APP_ENV');
        $js_data['columns'] = $data['columns'];
        $js_data['pk'] = $data['pk'];
        // $js_data['prefix'] = $data['prefix'];
        $js_data['status'] = config('constants.STATUS');
        $js_data['color'] = config('constants.COLOR_GENERAL');
    ?>
@endsection

@section('custom-scripts')

    @include('layouts.script_loaders.datatable_global')
    @include('layouts.script_loaders.excel_loader')
    <script src="{{ asset('/js/common/chosen.jquery.min.js') }}" type="text/javascript"></script>
    <script type="text/javascript" src="{{ asset('/js/notify.js') }}"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            
            // initialize datatables
            var view = {
                display_name : "view",
                class : "view",
                title : "View",
                url : "/",
                href : true,
                i : {
                    class : "fa fa-eye width_icon clr-sk"
                }
            };
            var edit = {
                display_name : "edit",
                class : "edit",
                title : "Edit",
                url : "/edit",
                href : true,
                i : {
                    class : "fa fa-pencil width_icon clr-sk"
                }
            };
            var remove = {
                display_name : "delete",
                class : "delete",
                title : "Delete",
                url : "/",
                href : false,
                i : {
                    class : "fa fa-trash width_icon clr-sk"
                }
            };

            var actionArr = [view, edit,remove];
            // var actionResult = getActionIconAcl(actionArr);
            var action_obj = actionArr;

            var datatable_object = {
                table_name : $('table').attr('id'),
                order : {
                    state: false,
                    column : 1,
                    mode : "desc"
                },
                buttons : {
                    state : true,
                    colvis : true,
                    excel : {
                        state: true,
                        columns: [$('thead th:not(".thead_action")')] 
                    },
                    pdf : {
                        state: true,
                        columns: [$('thead th:not(".thead_action")')] 
                    },
                    csv : {
                        state: true,
                        columns: [$('thead th:not(".thead_action")')] 
                    },
                    copy : {
                        state: true,
                        columns: [$('thead th:not(".thead_action")')] 
                    }
                },
                info : true,
                paging : true,
                searching : true,
                ordering : true,
                iDisplayLength: 10,
                sort_disabled_targets : [],
                ajax_url : window.location.href,
                column_data : datatableColumn(lang.columns, action_obj, lang.pk),
            }

            table = datatableInitGeneral(datatable_object);         


           
    });
    </script>

@endsection

resources/views/role/role_operation.blade.php
@extends('layouts.app')

@section('custom-styles')
  
    @include('layouts.style_loaders.token_loader')
    <link href="{{ asset('/css/common/chosen.min.css') }}" rel="stylesheet" type="text/css" />

@endsection

@section('htmlheader_title')
    @include('layouts.custom_partials.htmlheader_title', ['title' => (isset($data) && isset($data['name']) ? $data['name'] : '')])
@endsection


@section('contentheader_title')
    
    @include('layouts.custom_partials.contentheader_title', ['title' => (isset($data) && isset($data['name']) ? $data['name'] : '')])

@endsection

@section('custom-breadcrumb')
    @include('layouts.custom_partials.breadcrumb')
@endsection

@section('contentheader_description')
@endsection

@section('main-content')

@if (Request::segment(4))
    {!! Form::model($data, ['url' => ["/".Request::segment(1)."/".Request::segment(2), $data->getRouteKey()], 'method' => 'put']) !!}
@else
    {!! Form::open(['url' => "/".Request::segment(1)."/".Request::segment(2)]) !!}
@endif
<input type="hidden" name="screen_name" value = "{{(isset($data) && isset($data['screen_name'])) ? $data['screen_name'] : ''}}">

<section class="panel">
    <div class="panel-body">
        <div class = "row">
            <div class = "col-md-3">
                <div class="form-group">
                    <label for="name">Role Name *</label>
                    <input type="text" class="form-control title" id="name" name = "name" placeholder="Enter Role Name" value = "{{htmlValue('name', $data)}}">
                </div>
            </div>
            <div class = "col-md-6">
                <div class="form-group">
                    <label for="description">Role Description</label>
                    <input type="text" class="form-control" id="description" name = "description" placeholder="Enter Role Description" value = "{{htmlValue('description', $data)}}">
                </div>
            </div>
        </div>
    </div>
    
</section>
<section class="panel">
    <div class="panel-heading ">
        <label>Select Features</label>
    </div>
    <div class="panel-body">
        @foreach($data['tab'] as $key => $tab)     
            <div class="checkbox checkbox-sharekhan">
                <input type="checkbox" name="parent_tab" class = "styled parent_tab checkCBox" id = "{{$tab['id']}}" >
                <label>{{$key}}</label>
            </div>
            <div class = "row child_tab">

                @foreach($data['tab'][$key]['inner_tab'] as $innerkey => $innertab)
                    <div class = "col-md-3">
                        <ul>
                            <li>
                                <div class="checkbox checkbox-sharekhan">
                                    <input type="checkbox" name="inner_tab" class = "styled inner_tab checkCBox" id = "{{$innertab['id']}}">
                                    <label>{{$innerkey}}</label>
                                </div>
                                <ul>
                                     @foreach($data['tab'][$key]['inner_tab'][$innerkey]['permission_name'] as $permKey => $perm)
                                        <li>
                                            <?php 
                                                $tab = strtolower(str_replace(' ', '-', $key));
                                                $inner_tab = strtolower(str_replace(' ', '-', $innerkey));
                                                $permKey = strtolower(str_replace(' ', '-', $permKey));
                                                $val = 'permission['.$tab.']'.'['.$inner_tab.']'.'['.$permKey.']';

                                                if (isset($data) && isset($data['permission']) && isset($data['permission'][$tab]) && isset($data['permission'][$tab][$inner_tab]) && isset($data['permission'][$tab][$inner_tab][$permKey])) {
                                                    $checked = "checked";
                                                } else {
                                                    $checked = "";
                                                }
                                            ?>

                                            <div class="checkbox checkbox-sharekhan">
                                                <input type="checkbox" name='{{$val}}'' class = "styled permission checkCBox" id = "{{$perm['id']}}" dependent_id = "{{$perm['dependent_id']}}" value = {{$permKey}} {{$checked}}>
                                                <label>{{$permKey}}</label>
                                            </div>
                                        </li> 
                                    @endforeach
                                    
                                </ul>
                            </li>
                        </ul>
                    </div>
                @endforeach
            </div>       
            <hr>
        @endforeach
    </div>
</section>
@include('layouts.custom_partials.save_panel')
{!! Form::close() !!}
@endsection

@section('php-to-js')
    <?php
        $js_data = array();
        $js_data['env'] = env('APP_ENV');
    ?>
@endsection

@section('custom-scripts')
    
    <script src="{{ asset('/js/common/chosen.jquery.min.js') }}" type="text/javascript"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        chosenInit();
        disableAll("{{Request::segment(2)}}", "{{Route::currentRouteName()}}");
        
        $('.btn-success').prop('disabled',true);

        $(document).on('change',':checkbox', function() {
            if ($("input:checkbox:checked").length > 2)
           {
                console.log($('#name').val(),'jhvj');
                if($('#name').val() != ''){
                    // $('.btn-success').prop('disabled',true);
                }
           }   
           else
           {

                $('.btn-success').prop('disabled',false);
           }
        });

        $('.sidebar > ul > li > a').each(function() {
            // console.log($(this).text())
            $(this).parent().find('ul > li').each(function() {
            // console.log($(this).find('a').text())
            })
        });

        $(document).on('change', '.parent_tab', function() {
            var that = this;
            if ($(that).is(':checked')) {
                $(that).closest('div').next('.child_tab').find('input').prop('checked', true);
            } else {
                
                $(that).closest('div').next('.child_tab').find('input').prop('checked', false);
            }

            if ($("input:checkbox:checked").length > 2)
           {
                if($('#name').val() != ''){
                    $('.btn-success').prop('disabled',false);
                }
                
           }   
           else
           {
                $('.btn-success').prop('disabled',true);
           }
        });

        $(document).on('change', '.inner_tab', function() {
            if ($(this).is(':checked')) {
                $(this).closest('div').siblings('ul').find('input').prop('checked', true);
            } else {
                $(this).closest('div').siblings('ul').find('input').prop('checked', false);
            }
            
            if ($("input:checkbox:checked").length > 2)
           {
                if($('#name').val() != ''){
                    $('.btn-success').prop('disabled',false);
                }
           }   
           else
           {
                $('.btn-success').prop('disabled',true);
           }
            checkParentTab();
        });

        $(document).on('change', '.permission', function() {
            
            var ul = $(this).closest('ul');
            var i_checked = $(ul).find('input:checked').length;
            var i_total = $(ul).find('input').length;

            var d_i = $(ul).find('input:checked').attr('dependent_id');
           
            checkDependent(ul ,d_i);            
            
            checkInnerTab(ul, i_checked, i_total);
            checkParentTab();

            if ($("input:checkbox:checked").length > 2)
           {
                if($('#name').val() != ''){
                    $('.btn-success').prop('disabled',false);
                }
           }   
           else
           {
                $('.btn-success').prop('disabled',true);
           }
        });

        $(document).on('keyup','#name',function(){
            if ($("input:checkbox:checked").length > 2)
           {
                if($('#name').val() != ''){
                    $('.btn-success').prop('disabled',false);
                }
           }   
           else
           {
                $('.btn-success').prop('disabled',true);
           }
        })

        /*$(document).on('keyup', '.title', function() {
                var id = $(this).val();
                console.log(id);
                $.ajax({
                    type: 'get',
                    url:'/access-control/role/checkTitle',
                    data : {
                        entity : 'check-name',
                        entity_val : id
                    },
                    success: function(res){
                        console.log(1);
                        if(res != 0) {
                            console.log($('.title').parent());
                            $('.title').parent().addClass('has-error');
                            var p = "<p class = 'help-block error'>Name already exists</p>";
                            $('.title').siblings('p').remove();
                            $('.title').parent().append(p);
                            $('#save_continue').prop('disabled', true);
                            $('#save_return').prop('disabled', true);
                            } else {
                                $('.title').parent().removeClass('has-error');
                                $('.title').siblings('p').remove();
                                $('#save_continue').prop('disabled', false);
                                $('#save_return').prop('disabled', false);
                            }

                        }       
                });
            });*/



        function checkDependent(ul, d) {
            
            var t = $(ul).find('[dependent_id="'+d+'"]:checked').length;

            if(t) {
                if (isNaN(d)) {
                    d = d.split(",").map(Number);
                    if (Array.isArray(d)) {
                        $.each(d, function(k, v) {
                            $(ul).find('#'+v).prop('checked', true);
                        })
                    }
                } else {
                    $(ul).find('#'+d).prop('checked', true);
                }
            } else {
                $(ul).find('#'+d).prop('checked', false);
            }

        }

        function checkInnerTab(ul, checked, total) {
            if (checked == total) {
                $(ul).siblings('div').find('input').prop('checked', true);
            } else {
                $(ul).siblings('div').find('input').prop('checked', false);
            }
        }

        function checkInnerWhileLoad() {
            $('.child_tab div ul ul').each(function(k, v) {
                var i_checked = $(v).find('input:checked').length;
                
                var i_total = $(v).find('input').length;
                checkInnerTab(v, i_checked, i_total)
            })
        }

        checkInnerWhileLoad();

        function checkParentTab() {
            var checked = $('.inner_tab:checked').length;
            var total = $('.inner_tab').length;
            if (checked == total) {
                $('.parent_tab').prop('checked', true);
            } else {
                $('.parent_tab').prop('checked', false);
            }
        }

        checkParentTab();
    });

    </script>

@endsection

resources/views/role/show.blade.php
@extends('layouts.app')


@section('main-content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show Role</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('role.index') }}"> Back</a>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {{ $role->name }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Permissions:</strong>
            @if(!empty($rolePermissions))
                @foreach($rolePermissions as $v)
                    <label class="label label-success">{{ $v->name }},</label>
                @endforeach
            @endif
        </div>
    </div>
</div>
@endsection